
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("postgresql://neondb_owner:npg_Z3hgWDCxq4VL@ep-super-fog-amkyqbhi-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require"),
  },
});
